import {
  PendingOperation,
  LowStockProduct,
  RecentActivityItem,
  MovementSummaryData,
  DashboardFiltersState,
} from './types'

export const DEFAULT_FILTERS: DashboardFiltersState = {
  documentType: 'all',
  status: 'all',
  warehouse: 'all',
  category: 'all',
  searchQuery: '',
}

export const WAREHOUSE_OPTIONS = [
  { id: 'all', name: 'All Warehouses' },
  { id: 'WH01', name: 'WH01 — Main Central Warehouse' },
  { id: 'WH02', name: 'WH02 — North Distribution Hub' },
  { id: 'WH03', name: 'WH03 — Cold Storage Facility' },
]

export const CATEGORY_OPTIONS = [
  'All Categories',
  'Raw Materials',
  'Finished Goods',
  'Packaging',
  'Electronics',
  'Office Supplies',
]

export const DOCUMENT_TYPE_OPTIONS: { id: DashboardFiltersState['documentType']; label: string }[] = [
  { id: 'all', label: 'All Operations' },
  { id: 'receipts', label: 'Receipts' },
  { id: 'deliveries', label: 'Deliveries' },
  { id: 'transfers', label: 'Transfers' },
  { id: 'adjustments', label: 'Adjustments' },
]

export const STATUS_OPTIONS: { id: DashboardFiltersState['status']; label: string }[] = [
  { id: 'all', label: 'All Statuses' },
  { id: 'draft', label: 'Draft' },
  { id: 'waiting', label: 'Waiting' },
  { id: 'ready', label: 'Ready' },
  { id: 'done', label: 'Done' },
  { id: 'cancelled', label: 'Canceled' },
]

// ── Realistic Pending Operations ─────────────────────────────────────────────
export const INITIAL_PENDING_OPERATIONS: PendingOperation[] = [
  {
    id: 'op-001',
    reference: 'WH/IN/00142',
    type: 'receipt',
    source: 'Vendor: Apex Microtech Ltd',
    destination: 'WH01/Inbound Staging',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    partner: 'Apex Microtech Ltd',
    scheduledDate: 'Today, 14:00',
    itemCount: 4,
    totalUnits: 320,
    status: 'ready',
    priority: 'urgent',
    category: 'Electronics',
  },
  {
    id: 'op-002',
    reference: 'WH/OUT/00289',
    type: 'delivery',
    source: 'WH01/Bay 04',
    destination: 'Customer: Global Logistics Direct',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    partner: 'Global Logistics Direct',
    scheduledDate: 'Today, 16:30',
    itemCount: 12,
    totalUnits: 145,
    status: 'waiting',
    priority: 'urgent',
    category: 'Finished Goods',
  },
  {
    id: 'op-003',
    reference: 'WH/INT/00094',
    type: 'transfer',
    source: 'WH01/Bulk Staging A',
    destination: 'WH02/Pick Zone 1',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    scheduledDate: 'Today, 17:00',
    itemCount: 6,
    totalUnits: 210,
    status: 'ready',
    priority: 'normal',
    category: 'Packaging',
  },
  {
    id: 'op-004',
    reference: 'WH/IN/00143',
    type: 'receipt',
    source: 'Vendor: Nordic Timber Co.',
    destination: 'WH02/Unloading Bay',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    partner: 'Nordic Timber Co.',
    scheduledDate: 'Tomorrow, 09:30',
    itemCount: 2,
    totalUnits: 500,
    status: 'draft',
    priority: 'normal',
    category: 'Raw Materials',
  },
  {
    id: 'op-005',
    reference: 'WH/OUT/00290',
    type: 'delivery',
    source: 'WH03/Cold Zone C-2',
    destination: 'Customer: FreshFoods Retail Corp',
    warehouseId: 'WH03',
    warehouseName: 'WH03 — Cold Storage Facility',
    partner: 'FreshFoods Retail Corp',
    scheduledDate: 'Today, 18:00',
    itemCount: 8,
    totalUnits: 80,
    status: 'ready',
    priority: 'urgent',
    category: 'Raw Materials',
  },
  {
    id: 'op-006',
    reference: 'WH/ADJ/00028',
    type: 'adjustment',
    source: 'WH02/Aisle 12',
    destination: 'Virtual/Scrap & Discrepancy',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    scheduledDate: 'Tomorrow, 11:00',
    itemCount: 3,
    totalUnits: 18,
    status: 'draft',
    priority: 'normal',
    category: 'Office Supplies',
  },
  {
    id: 'op-007',
    reference: 'WH/INT/00095',
    type: 'transfer',
    source: 'WH02/Overstock Rack 9',
    destination: 'WH01/Forward Pick Bay',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    scheduledDate: 'Tomorrow, 14:00',
    itemCount: 5,
    totalUnits: 110,
    status: 'waiting',
    priority: 'normal',
    category: 'Finished Goods',
  },
  {
    id: 'op-008',
    reference: 'WH/OUT/00291',
    type: 'delivery',
    source: 'WH01/Shipping Staging',
    destination: 'Customer: TechVibe Hardware Inc',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    partner: 'TechVibe Hardware Inc',
    scheduledDate: 'Today, 19:15',
    itemCount: 15,
    totalUnits: 92,
    status: 'ready',
    priority: 'normal',
    category: 'Electronics',
  },
]

// ── Realistic Low Stock & Out of Stock Products ──────────────────────────────
export const INITIAL_LOW_STOCK_PRODUCTS: LowStockProduct[] = [
  {
    id: 'prod-001',
    sku: 'SKU-ERG-904',
    name: 'Ergonomic Task Chair (Mesh Black)',
    category: 'Finished Goods',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    onHand: 4,
    minLevel: 25,
    reorderQuantity: 50,
    unit: 'pcs',
    status: 'low_stock',
    lastRestocked: '12 days ago',
  },
  {
    id: 'prod-002',
    sku: 'SKU-CBL-102',
    name: 'Braided Thunderbolt 4 Cable 2m',
    category: 'Electronics',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    onHand: 0,
    minLevel: 40,
    reorderQuantity: 100,
    unit: 'pcs',
    status: 'out_of_stock',
    lastRestocked: '3 weeks ago',
  },
  {
    id: 'prod-003',
    sku: 'SKU-PKG-440',
    name: 'Heavy-Duty Corrugated Carton Box 40x30x30',
    category: 'Packaging',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    onHand: 28,
    minLevel: 200,
    reorderQuantity: 500,
    unit: 'pcs',
    status: 'low_stock',
    lastRestocked: '6 days ago',
  },
  {
    id: 'prod-004',
    sku: 'SKU-PLT-008',
    name: 'Euro Pallet Hardwood Treated 120x80',
    category: 'Raw Materials',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    onHand: 2,
    minLevel: 50,
    reorderQuantity: 120,
    unit: 'units',
    status: 'low_stock',
    lastRestocked: '18 days ago',
  },
  {
    id: 'prod-005',
    sku: 'SKU-SEN-910',
    name: 'Temperature & Humidity IoT Telemetry Probe',
    category: 'Electronics',
    warehouseId: 'WH03',
    warehouseName: 'WH03 — Cold Storage Facility',
    onHand: 0,
    minLevel: 15,
    reorderQuantity: 30,
    unit: 'pcs',
    status: 'out_of_stock',
    lastRestocked: '1 month ago',
  },
  {
    id: 'prod-006',
    sku: 'SKU-OFF-219',
    name: 'Thermal Shipping Label Rolls 4x6 (500/roll)',
    category: 'Office Supplies',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    onHand: 6,
    minLevel: 30,
    reorderQuantity: 60,
    unit: 'rolls',
    status: 'low_stock',
    lastRestocked: '9 days ago',
  },
  {
    id: 'prod-007',
    sku: 'SKU-INS-602',
    name: 'Thermal Insulation Foam Liner Sheets',
    category: 'Raw Materials',
    warehouseId: 'WH03',
    warehouseName: 'WH03 — Cold Storage Facility',
    onHand: 0,
    minLevel: 60,
    reorderQuantity: 150,
    unit: 'sheets',
    status: 'out_of_stock',
    lastRestocked: '2 weeks ago',
  },
]

// ── Realistic Recent Activity Feed ───────────────────────────────────────────
export const INITIAL_RECENT_ACTIVITIES: RecentActivityItem[] = [
  {
    id: 'act-001',
    reference: 'WH/IN/00141',
    type: 'receipt',
    description: 'PO-8840 Raw Aluminum Profiles Received (350 pcs)',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    category: 'Raw Materials',
    units: 350,
    unitLabel: 'pcs',
    status: 'done',
    user: 'D. Miller',
    timestamp: '11:15 AM',
    relativeTime: '14 mins ago',
  },
  {
    id: 'act-002',
    reference: 'WH/OUT/00288',
    type: 'delivery',
    description: 'SO-4419 Commercial Freight Loaded & Dispatched (48 units)',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    category: 'Finished Goods',
    units: 48,
    unitLabel: 'units',
    status: 'done',
    user: 'K. Patel',
    timestamp: '10:48 AM',
    relativeTime: '41 mins ago',
  },
  {
    id: 'act-003',
    reference: 'WH/INT/00093',
    type: 'transfer',
    description: 'Stock Relocation: Staging Bay 3 → High-Density Rack A-12',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    category: 'Electronics',
    units: 120,
    unitLabel: 'pcs',
    status: 'done',
    user: 'S. Ganesan',
    timestamp: '10:05 AM',
    relativeTime: '1 hr 24m ago',
  },
  {
    id: 'act-004',
    reference: 'WH/ADJ/00027',
    type: 'adjustment',
    description: 'Cycle Count Variance Confirmed: Bin C-04 (-2 pcs damaged)',
    warehouseId: 'WH03',
    warehouseName: 'WH03 — Cold Storage Facility',
    category: 'Raw Materials',
    units: 2,
    unitLabel: 'pcs',
    status: 'done',
    user: 'M. Chen',
    timestamp: '09:22 AM',
    relativeTime: '2 hrs ago',
  },
  {
    id: 'act-005',
    reference: 'WH/IN/00140',
    type: 'receipt',
    description: 'PO-8839 Fasteners & Hardware Intake Validated (1,200 pcs)',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    category: 'Raw Materials',
    units: 1200,
    unitLabel: 'pcs',
    status: 'done',
    user: 'J. Rodriguez',
    timestamp: '08:50 AM',
    relativeTime: '2 hrs 40m ago',
  },
  {
    id: 'act-006',
    reference: 'WH/OUT/00287',
    type: 'delivery',
    description: 'SO-4415 Priority Courier Consignment Awaiting Carrier',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    category: 'Packaging',
    units: 64,
    unitLabel: 'cartons',
    status: 'ready',
    user: 'D. Miller',
    timestamp: '08:15 AM',
    relativeTime: '3 hrs ago',
  },
  {
    id: 'act-007',
    reference: 'WH/INT/00092',
    type: 'transfer',
    description: 'Inter-warehouse Transit: WH01 Central → WH03 Cold Zone',
    warehouseId: 'WH03',
    warehouseName: 'WH03 — Cold Storage Facility',
    category: 'Raw Materials',
    units: 75,
    unitLabel: 'cases',
    status: 'confirmed',
    user: 'System Bot',
    timestamp: 'Yesterday',
    relativeTime: '1 day ago',
  },
]

// ── Realistic Movement Summary ───────────────────────────────────────────────
export const INITIAL_MOVEMENT_DATA: MovementSummaryData = {
  inboundUnits: 1550,
  inboundCount: 14,
  outboundUnits: 890,
  outboundCount: 29,
  internalUnits: 405,
  internalCount: 7,
  adjustmentsUnits: 20,
  adjustmentsCount: 3,
  netChange: 660, // 1550 inbound - 890 outbound
  byWarehouse: [
    {
      warehouseId: 'WH01',
      name: 'WH01 — Main Central Warehouse',
      inbound: 870,
      outbound: 520,
      internal: 210,
      utilization: '74% Capacity',
    },
    {
      warehouseId: 'WH02',
      name: 'WH02 — North Distribution Hub',
      inbound: 500,
      outbound: 290,
      internal: 120,
      utilization: '52% Capacity',
    },
    {
      warehouseId: 'WH03',
      name: 'WH03 — Cold Storage Facility',
      inbound: 180,
      outbound: 80,
      internal: 75,
      utilization: '88% Capacity',
    },
  ],
}
