import { StockMove } from './types'

export const INITIAL_MOVES: StockMove[] = [
  {
    id: 'mov-101',
    transactionId: 'TX-2026-99042',
    timestamp: '2026-09-26 11:15',
    date: '2026-09-26',
    time: '11:15',
    productId: 'prod-010',
    productSku: 'SKU-ALU-501',
    productName: 'Extruded Aluminum Profile 40x40 T-Slot 2m',
    productCategory: 'Raw Materials',
    movementType: 'receipt',
    sourceLocation: 'Vendor: Apex Metal Works',
    destinationLocation: 'WH01/Production Floor',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: 350,
    unit: 'meters',
    reference: 'WH/IN/00141',
    referenceUrl: '/operations/receipts/rec-003',
    user: 'D. Miller',
    notes: 'Structural frame extrusions inspected and signed off by quality control.',
  },
  {
    id: 'mov-102',
    transactionId: 'TX-2026-99041',
    timestamp: '2026-09-26 10:45',
    date: '2026-09-26',
    time: '10:45',
    productId: 'prod-001',
    productSku: 'SKU-ERG-904',
    productName: 'Ergonomic Task Chair (Mesh Black)',
    productCategory: 'Finished Goods',
    movementType: 'delivery',
    sourceLocation: 'WH01/Rack A',
    destinationLocation: 'Customer: Global Logistics',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: -12,
    unit: 'pcs',
    reference: 'WH/OUT/00288',
    referenceUrl: '/operations/deliveries/del-001',
    user: 'K. Patel',
    notes: 'Standard ground freight dispatch for commercial office rollout.',
  },
  {
    id: 'mov-103',
    transactionId: 'TX-2026-99040',
    timestamp: '2026-09-26 10:30',
    date: '2026-09-26',
    time: '10:30',
    productId: 'prod-001',
    productSku: 'SKU-ERG-904',
    productName: 'Ergonomic Task Chair (Mesh Black)',
    productCategory: 'Finished Goods',
    movementType: 'adjustment',
    sourceLocation: 'WH01/Rack A',
    destinationLocation: 'Scrap Quarantine / Write-off',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: -3,
    unit: 'pcs',
    reference: 'WH/ADJ/00035',
    referenceUrl: '/operations/adjustments/adj-001',
    user: 'Alex Mercer',
    notes: '3 units with cracked caster assemblies isolated during aisle 4 cycle count.',
  },
  {
    id: 'mov-104',
    transactionId: 'TX-2026-99039',
    timestamp: '2026-09-26 10:20',
    date: '2026-09-26',
    time: '10:20',
    productId: 'prod-001',
    productSku: 'SKU-ERG-904',
    productName: 'Ergonomic Task Chair (Mesh Black)',
    productCategory: 'Finished Goods',
    movementType: 'transfer',
    sourceLocation: 'WH01/Production Floor',
    destinationLocation: 'WH01/Rack B',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: 15,
    unit: 'pcs',
    reference: 'WH/INT/00091',
    referenceUrl: '/operations/transfers/trf-002',
    user: 'S. Ganesan',
    notes: 'Line clearing from manufacturing assembly back to primary storage rack.',
  },
  {
    id: 'mov-105',
    transactionId: 'TX-2026-99038',
    timestamp: '2026-09-26 09:15',
    date: '2026-09-26',
    time: '09:15',
    productId: 'prod-006',
    productSku: 'SKU-MON-881',
    productName: 'Dual Arm VESA Monitor Mount Heavy-Duty',
    productCategory: 'Electronics',
    movementType: 'receipt',
    sourceLocation: 'Vendor: MountTech Corp',
    destinationLocation: 'WH01/Rack A',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: 120,
    unit: 'pcs',
    reference: 'WH/IN/00140',
    referenceUrl: '/operations/receipts/rec-004',
    user: 'D. Miller',
    notes: 'Intake batch received from supplier and put away in Section A.',
  },
  {
    id: 'mov-106',
    transactionId: 'TX-2026-99037',
    timestamp: '2026-09-25 15:45',
    date: '2026-09-25',
    time: '15:45',
    productId: 'prod-005',
    productSku: 'SKU-PLT-008',
    productName: 'Euro Pallet Hardwood Treated 120x80',
    productCategory: 'Raw Materials',
    movementType: 'adjustment',
    sourceLocation: 'WH02/Staging Area 1',
    destinationLocation: 'Damaged Salvage Bay',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    quantity: -1,
    unit: 'units',
    reference: 'WH/ADJ/00034',
    referenceUrl: '/operations/adjustments/adj-002',
    user: 'Alex Mercer',
    notes: 'Forklift blade impact damaged base runner beyond structural tolerance.',
  },
  {
    id: 'mov-107',
    transactionId: 'TX-2026-99036',
    timestamp: '2026-09-25 14:15',
    date: '2026-09-25',
    time: '14:15',
    productId: 'prod-002',
    productSku: 'SKU-DKS-301',
    productName: 'Motorized Standing Desk Frame 140cm',
    productCategory: 'Finished Goods',
    movementType: 'delivery',
    sourceLocation: 'WH01/Rack B',
    destinationLocation: 'Customer: TechDesign Studio',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: -6,
    unit: 'pcs',
    reference: 'WH/OUT/00285',
    referenceUrl: '/operations/deliveries/del-002',
    user: 'K. Patel',
    notes: 'Express courier delivery for architectural firm studio setup.',
  },
  {
    id: 'mov-108',
    transactionId: 'TX-2026-99035',
    timestamp: '2026-09-24 16:30',
    date: '2026-09-24',
    time: '16:30',
    productId: 'prod-010',
    productSku: 'SKU-ALU-501',
    productName: 'Extruded Aluminum Profile 40x40 T-Slot 2m',
    productCategory: 'Raw Materials',
    movementType: 'adjustment',
    sourceLocation: 'Unassigned Stock Buffer',
    destinationLocation: 'WH01/Production Floor',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: 20,
    unit: 'meters',
    reference: 'WH/ADJ/00036',
    referenceUrl: '/operations/adjustments/adj-003',
    user: 'David Miller',
    notes: 'Unlabeled bundle from previous shift fabrication identified during floor sweep.',
  },
  {
    id: 'mov-109',
    transactionId: 'TX-2026-99034',
    timestamp: '2026-09-24 14:15',
    date: '2026-09-24',
    time: '14:15',
    productId: 'prod-004',
    productSku: 'SKU-PKG-440',
    productName: 'Heavy-Duty Corrugated Carton Box 40x30x30',
    productCategory: 'Packaging',
    movementType: 'transfer',
    sourceLocation: 'WH02/Unloading Bay',
    destinationLocation: 'WH02/Rack 04',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    quantity: 200,
    unit: 'cartons',
    reference: 'WH/INT/00088',
    referenceUrl: '/operations/transfers/trf-004',
    user: 'Marcus Chen',
    notes: 'Putaway transfer from inbound unloading staging into high-density storage rack.',
  },
  {
    id: 'mov-110',
    transactionId: 'TX-2026-99033',
    timestamp: '2026-09-24 11:30',
    date: '2026-09-24',
    time: '11:30',
    productId: 'prod-002',
    productSku: 'SKU-DKS-301',
    productName: 'Motorized Standing Desk Frame 140cm',
    productCategory: 'Finished Goods',
    movementType: 'receipt',
    sourceLocation: 'Vendor: DeskCraft Ltd',
    destinationLocation: 'WH01/Rack B',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: 10,
    unit: 'pcs',
    reference: 'WH/IN/00135',
    referenceUrl: '/operations/receipts/rec-001',
    user: 'David Miller',
    notes: 'Replenishment delivery intake PO-8812.',
  },
  {
    id: 'mov-111',
    transactionId: 'TX-2026-99032',
    timestamp: '2026-09-23 14:30',
    date: '2026-09-23',
    time: '14:30',
    productId: 'prod-001',
    productSku: 'SKU-ERG-904',
    productName: 'Ergonomic Task Chair (Mesh Black)',
    productCategory: 'Finished Goods',
    movementType: 'receipt',
    sourceLocation: 'Vendor: ErgoFab Industries',
    destinationLocation: 'WH01/Rack A',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: 100,
    unit: 'pcs',
    reference: 'WH/IN/00139',
    referenceUrl: '/operations/receipts/rec-004',
    user: 'J. Rodriguez',
    notes: 'Large component batch received and added to on-hand inventory.',
  },
  {
    id: 'mov-112',
    transactionId: 'TX-2026-99031',
    timestamp: '2026-09-22 16:45',
    date: '2026-09-22',
    time: '16:45',
    productId: 'prod-004',
    productSku: 'SKU-PKG-440',
    productName: 'Heavy-Duty Corrugated Carton Box 40x30x30',
    productCategory: 'Packaging',
    movementType: 'delivery',
    sourceLocation: 'WH02/Staging Area 1',
    destinationLocation: 'Internal Pack Station B',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    quantity: -150,
    unit: 'cartons',
    reference: 'WH/OUT/00270',
    referenceUrl: '/operations/deliveries/del-003',
    user: 'Marcus Chen',
    notes: 'Packaging consumption requisition for high-volume shipment dispatch.',
  },
  {
    id: 'mov-113',
    transactionId: 'TX-2026-99030',
    timestamp: '2026-09-20 17:00',
    date: '2026-09-20',
    time: '17:00',
    productId: 'prod-002',
    productSku: 'SKU-DKS-301',
    productName: 'Motorized Standing Desk Frame 140cm',
    productCategory: 'Finished Goods',
    movementType: 'adjustment',
    sourceLocation: 'WH01/Rack B',
    destinationLocation: 'WH01/Rack B',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: 0,
    unit: 'pcs',
    reference: 'WH/ADJ/00032',
    referenceUrl: '/operations/adjustments/adj-005',
    user: 'Elena Rostova',
    notes: 'Quarterly shelf audit verified 100% stock count accuracy (zero discrepancy).',
  },
  {
    id: 'mov-114',
    transactionId: 'TX-2026-99029',
    timestamp: '2026-09-17 11:20',
    date: '2026-09-17',
    time: '11:20',
    productId: 'prod-008',
    productSku: 'SKU-OFF-219',
    productName: 'Thermal Shipping Label Rolls 4x6 (500/roll)',
    productCategory: 'Office Supplies',
    movementType: 'delivery',
    sourceLocation: 'WH01/Rack B',
    destinationLocation: 'Warehouse Dispatch Table',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: -12,
    unit: 'rolls',
    reference: 'WH/OUT/00262',
    referenceUrl: '/operations/deliveries/del-004',
    user: 'K. Patel',
    notes: 'Shipping desk label consumable replenishment.',
  },
  {
    id: 'mov-115',
    transactionId: 'TX-2026-99028',
    timestamp: '2026-09-08 14:00',
    date: '2026-09-08',
    time: '14:00',
    productId: 'prod-005',
    productSku: 'SKU-PLT-008',
    productName: 'Euro Pallet Hardwood Treated 120x80',
    productCategory: 'Raw Materials',
    movementType: 'transfer',
    sourceLocation: 'WH02/Yard 2',
    destinationLocation: 'WH02/Staging Area 1',
    warehouseId: 'WH02',
    warehouseName: 'WH02 — North Distribution Hub',
    quantity: 20,
    unit: 'units',
    reference: 'WH/INT/00078',
    referenceUrl: '/operations/transfers/trf-001',
    user: 'David Miller',
    notes: 'Outdoor staging transfer into covered distribution bay.',
  },
  {
    id: 'mov-116',
    transactionId: 'TX-2026-99027',
    timestamp: '2026-09-05 10:15',
    date: '2026-09-05',
    time: '10:15',
    productId: 'prod-003',
    productSku: 'SKU-CBL-102',
    productName: 'Braided Thunderbolt 4 Cable 2m',
    productCategory: 'Electronics',
    movementType: 'delivery',
    sourceLocation: 'WH01/Rack A',
    destinationLocation: 'Customer: PrimeTech Corp',
    warehouseId: 'WH01',
    warehouseName: 'WH01 — Main Central Warehouse',
    quantity: -40,
    unit: 'pcs',
    reference: 'WH/OUT/00250',
    referenceUrl: '/operations/deliveries/del-005',
    user: 'K. Patel',
    notes: 'Bulk enterprise cable dispatch. Depleted on-hand inventory to zero.',
  },
]

let movesStore = [...INITIAL_MOVES]

export function getMockMoves(): StockMove[] {
  return [...movesStore]
}

export function getMockMoveById(id: string): StockMove | undefined {
  return movesStore.find((m) => m.id === id || m.transactionId === id)
}
