import { Warehouse } from './types'

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-001',
    code: 'WH01',
    name: 'Main Central Warehouse',
    address: 'Section A-D, Logistics Park North, Bldg 4, Frankfurt DE',
    manager: 'Alex Mercer (Lead Inventory Ops)',
    status: 'active',
    totalLocations: 5,
    productCount: 5,
    totalStockUnits: 906,
    capacityUtilization: 74,
    lowStockCount: 1,
    outOfStockCount: 1,
    locations: [
      {
        id: 'loc-wh01-rack-a',
        name: 'Rack A',
        fullPath: 'WH01/Rack A',
        type: 'rack',
        itemCount: 2,
        totalUnits: 295,
        description: 'Multi-tier selective pallet racking for finished goods',
        products: [
          {
            id: 'prod-001',
            sku: 'SKU-ERG-904',
            name: 'Ergonomic Task Chair (Mesh Black)',
            category: 'Finished Goods',
            quantity: 85,
            unit: 'pcs',
            status: 'in_stock',
            minReorderLevel: 25,
          },
          {
            id: 'prod-006',
            sku: 'SKU-MON-881',
            name: 'Dual Arm VESA Monitor Mount Heavy-Duty',
            category: 'Electronics',
            quantity: 210,
            unit: 'pcs',
            status: 'in_stock',
            minReorderLevel: 50,
          },
        ],
      },
      {
        id: 'loc-wh01-rack-b',
        name: 'Rack B',
        fullPath: 'WH01/Rack B',
        type: 'rack',
        itemCount: 4,
        totalUnits: 168,
        description: 'Medium-density cantilever racking and bin shelving',
        products: [
          {
            id: 'prod-002',
            sku: 'SKU-DKS-301',
            name: 'Motorized Standing Desk Frame 140cm',
            category: 'Finished Goods',
            quantity: 20,
            unit: 'pcs',
            status: 'in_stock',
            minReorderLevel: 15,
          },
          {
            id: 'prod-001',
            sku: 'SKU-ERG-904',
            name: 'Ergonomic Task Chair (Mesh Black)',
            category: 'Finished Goods',
            quantity: 42,
            unit: 'pcs',
            status: 'in_stock',
            minReorderLevel: 25,
          },
          {
            id: 'prod-006',
            sku: 'SKU-MON-881',
            name: 'Dual Arm VESA Monitor Mount Heavy-Duty',
            category: 'Electronics',
            quantity: 100,
            unit: 'pcs',
            status: 'in_stock',
            minReorderLevel: 50,
          },
          {
            id: 'prod-008',
            sku: 'SKU-OFF-219',
            name: 'Thermal Shipping Label Rolls 4x6 (500/roll)',
            category: 'Office Supplies',
            quantity: 6,
            unit: 'rolls',
            status: 'low_stock',
            minReorderLevel: 30,
          },
        ],
      },
      {
        id: 'loc-wh01-prod',
        name: 'Production Floor',
        fullPath: 'WH01/Production Floor',
        type: 'production',
        itemCount: 3,
        totalUnits: 443,
        description: 'Active assembly station buffer and machining intake staging',
        products: [
          {
            id: 'prod-010',
            sku: 'SKU-ALU-501',
            name: 'Extruded Aluminum Profile 40x40 T-Slot 2m',
            category: 'Raw Materials',
            quantity: 420,
            unit: 'meters',
            status: 'in_stock',
            minReorderLevel: 100,
          },
          {
            id: 'prod-001',
            sku: 'SKU-ERG-904',
            name: 'Ergonomic Task Chair (Mesh Black)',
            category: 'Finished Goods',
            quantity: 15,
            unit: 'pcs',
            status: 'in_stock',
            minReorderLevel: 25,
          },
          {
            id: 'prod-002',
            sku: 'SKU-DKS-301',
            name: 'Motorized Standing Desk Frame 140cm',
            category: 'Finished Goods',
            quantity: 8,
            unit: 'pcs',
            status: 'in_stock',
            minReorderLevel: 15,
          },
        ],
      },
      {
        id: 'loc-wh01-inbound',
        name: 'Inbound Staging',
        fullPath: 'WH01/Inbound Staging',
        type: 'staging',
        itemCount: 0,
        totalUnits: 0,
        description: 'Vendor receiving dock door 04 inspection & intake staging',
        products: [],
      },
      {
        id: 'loc-wh01-outbound',
        name: 'Outbound Dock',
        fullPath: 'WH01/Outbound Dock',
        type: 'dock',
        itemCount: 0,
        totalUnits: 0,
        description: 'Vehicle loading bays 01-03 for dispatched carrier shipments',
        products: [],
      },
    ],
  },
  {
    id: 'wh-002',
    code: 'WH02',
    name: 'North Distribution Hub',
    address: 'Freight Corridor 7, Intermodal Terminal, Hamburg DE',
    manager: 'Marcus Chen (Operations Supervisor)',
    status: 'active',
    totalLocations: 4,
    productCount: 2,
    totalStockUnits: 32,
    capacityUtilization: 52,
    lowStockCount: 2,
    outOfStockCount: 0,
    locations: [
      {
        id: 'loc-wh02-stage',
        name: 'Staging Area 1',
        fullPath: 'WH02/Staging Area 1',
        type: 'staging',
        itemCount: 2,
        totalUnits: 24,
        description: 'Pallet marshaling area for northern retail replenishment',
        products: [
          {
            id: 'prod-004',
            sku: 'SKU-PKG-440',
            name: 'Heavy-Duty Corrugated Carton Box 40x30x30',
            category: 'Packaging',
            quantity: 20,
            unit: 'cartons',
            status: 'low_stock',
            minReorderLevel: 200,
          },
          {
            id: 'prod-005',
            sku: 'SKU-PLT-008',
            name: 'Euro Pallet Hardwood Treated 120x80',
            category: 'Raw Materials',
            quantity: 4,
            unit: 'units',
            status: 'low_stock',
            minReorderLevel: 50,
          },
        ],
      },
      {
        id: 'loc-wh02-rack-4',
        name: 'Rack 04',
        fullPath: 'WH02/Rack 04',
        type: 'rack',
        itemCount: 1,
        totalUnits: 8,
        description: 'Narrow-aisle carton racking Bay 4',
        products: [
          {
            id: 'prod-004',
            sku: 'SKU-PKG-440',
            name: 'Heavy-Duty Corrugated Carton Box 40x30x30',
            category: 'Packaging',
            quantity: 8,
            unit: 'cartons',
            status: 'low_stock',
            minReorderLevel: 200,
          },
        ],
      },
      {
        id: 'loc-wh02-unload',
        name: 'Unloading Bay',
        fullPath: 'WH02/Unloading Bay',
        type: 'dock',
        itemCount: 0,
        totalUnits: 0,
        description: 'Container de-stuffing and intake bay',
        products: [],
      },
      {
        id: 'loc-wh02-dispatch',
        name: 'Dispatch Staging',
        fullPath: 'WH02/Dispatch Staging',
        type: 'staging',
        itemCount: 0,
        totalUnits: 0,
        description: 'Pre-load staging zone for regional hauliers',
        products: [],
      },
    ],
  },
  {
    id: 'wh-003',
    code: 'WH03',
    name: 'Cold Storage Facility',
    address: 'Zone Industrielle Sud, Cryo Unit 2, Lyon FR',
    manager: 'Elena Rostova (Cold Chain Specialist)',
    status: 'active',
    totalLocations: 3,
    productCount: 2,
    totalStockUnits: 0,
    capacityUtilization: 88,
    lowStockCount: 0,
    outOfStockCount: 2,
    locations: [
      {
        id: 'loc-wh03-zone-c',
        name: 'Zone C-1',
        fullPath: 'WH03/Zone C-1',
        type: 'zone',
        itemCount: 2,
        totalUnits: 0,
        description: 'Temperature-controlled chamber (-18°C to +4°C)',
        products: [
          {
            id: 'prod-007',
            sku: 'SKU-SEN-910',
            name: 'Temperature & Humidity IoT Telemetry Probe',
            category: 'Electronics',
            quantity: 0,
            unit: 'pcs',
            status: 'out_of_stock',
            minReorderLevel: 15,
          },
          {
            id: 'prod-009',
            sku: 'SKU-INS-602',
            name: 'Thermal Insulation Foam Liner Sheets',
            category: 'Raw Materials',
            quantity: 0,
            unit: 'meters',
            status: 'out_of_stock',
            minReorderLevel: 60,
          },
        ],
      },
      {
        id: 'loc-wh03-intake',
        name: 'Cold Intake Staging',
        fullPath: 'WH03/Cold Intake Staging',
        type: 'staging',
        itemCount: 0,
        totalUnits: 0,
        description: 'Rapid pull-down staging ante-room',
        products: [],
      },
      {
        id: 'loc-wh03-freeze',
        name: 'Deep Freeze Bay',
        fullPath: 'WH03/Deep Freeze Bay',
        type: 'zone',
        itemCount: 0,
        totalUnits: 0,
        description: 'Ultra-low temperature storage zone (-40°C)',
        products: [],
      },
    ],
  },
]

let warehousesStore = [...INITIAL_WAREHOUSES]

export function getMockWarehouses(): Warehouse[] {
  return [...warehousesStore]
}

export function getMockWarehouseById(id: string): Warehouse | undefined {
  return warehousesStore.find((w) => w.id === id || w.code === id)
}
